name = "ordergetitright-updater"
main = "src/index.js"
compatibility_date = "2024-01-01"

routes = [{ pattern = "update.ordergetitright.com/*", custom_domain = true }]

[[kv_namespaces]]
binding = "UPDATES_KV"
id = "f726dd2f0de24c32b8af87fef5e06895"

[[r2_buckets]]
binding = "RELEASES_BUCKET"
bucket_name = "ordergetitright-releases"

[observability]
enabled = true

[observability.logs]
enabled = true
head_sampling_rate = 1.0
