"""
ACL Demand Generator

Australian Consumer Law Section 56 demand letter generator.  Produces
a human-readable markdown document suitable for legal review.
"""
from datetime import datetime, timezone

from src.types import DeceptionReport
from config.constants import PROJECT_NAME, PROJECT_VERSION, PROJECT_OPERATOR


def generate_acl_demand(
    invoice_spec: str,
    hardware_id: str,
    deception_report: DeceptionReport,
    consumer_name: str = "[Consumer Name]",
    supplier_name: str = "[Supplier Name]",
    bbfb_score: dict = None,
) -> str:
    """Return a Section 56 demand letter as markdown."""
    date_issued = datetime.now(timezone.utc).date().isoformat()
    pattern_lines = "\n".join(
        f"- **{p.patternName}** ({p.patternId}): severity {p.severity}, "
        f"confidence {p.confidence * 100:.1f}%"
        for p in deception_report.detectedPatterns
    ) or "- No patterns detected"
    reasoning_lines = "\n".join(f"- {r}" for r in deception_report.forensicReasoning) or "- No forensic reasoning generated"

    bbfb_section = ""
    if bbfb_score:
        law_table = "\n".join(
            f"| {l['metric']} | {l['value']:.4f} | {l['threshold']} | {'YES' if l['passed'] else '**NO**'} |"
            for l in bbfb_score.get("law", [])
        )
        grace = bbfb_score.get("grace", {})
        fruit = bbfb_score.get("fruit", {})
        bbfb_section = f"""

### 3.5 BBFB Economic Harm Assessment

| LAW Gate | Value | Threshold | Passed |
|----------|-------|-----------|--------|
{law_table}

| GRACE Risk | Value |
|------------|-------|
| Raw Penalty | {grace.get('rawPenalty', 0):.4f} |
| Normalized Penalty | {grace.get('normalizedPenalty', 0):.4f} |
| Risk Level | **{grace.get('riskLevel', 'N/A')}** |

| FRUIT Score | Value |
|-------------|-------|
| Composite Value Score | {fruit.get('compositeValueScore', 0):.6f} |
| CVS Threshold | {fruit.get('threshold', 0)} |
| Compliant | {'YES' if fruit.get('compliant', False) else '**NO**'} |

**Overall BBFB Compliance**: {'COMPLIANT' if bbfb_score.get('overallCompliant', False) else '**NON-COMPLIANT -- Economic harm substantiated**'}
"""

    return f"""# FORMAL LEGAL DEMAND -- Australian Consumer Law Section 56

**Date Issued**: {date_issued}
**Reference**: OGIR-ACL56-{date_issued.replace('-', '')}
**Generated by**: {PROJECT_NAME} v{PROJECT_VERSION}

---

## 1. Parties

| Role | Name |
|------|------|
| **Consumer** | {consumer_name} |
| **Supplier** | {supplier_name} |

## 2. Material Breach -- Goods Do Not Match Description

| Item | Invoice Description | Actual Product | Discrepancy |
|------|---------------------|----------------|-------------|
| Model | {invoice_spec} | {hardware_id} | Specification mismatch |

## 3. Forensic Evidence

### 3.1 Entropy Analysis

| Metric | Value |
|--------|-------|
| Shannon Entropy | {deception_report.entropy.shannonEntropy:.3f} bits/char |
| Normalized Entropy | {deception_report.entropy.normalizedEntropy:.3f} |
| Anomaly Flag | {'YES -- possible non-human origin' if deception_report.entropy.anomalyFlag else 'No'} |

### 3.2 Deceptive Patterns Detected

{pattern_lines}

### 3.3 Deception Probability

**{deception_report.deceptionProbability * 100:.1f}%** -- Structural Deception Flag: **{'TRUE' if deception_report.structuralDeceptionFlag else 'FALSE'}**

### 3.4 Forensic Reasoning

{reasoning_lines}
{bbfb_section}
## 4. Demand

Pursuant to the Australian Consumer Law (Schedule 2 of the Competition and Consumer Act 2010), the consumer demands:

1. **Full refund** of the purchase price within **14 business days**; OR
2. **Replacement** with goods matching the invoice description exactly; OR
3. **Cost of correction** (including but not limited to DSP retuning, integration costs, and any consequential loss).

## 5. Consequences of Non-Compliance

Failure to comply within 14 business days will result in:

- Formal complaint to the **Australian Competition and Consumer Commission (ACCC)**
- Referral to the relevant **State/Territory Consumer Affairs office**
- Legal proceedings for breach of statutory consumer guarantees

## 6. Evidence Package

This demand is supported by the forensic audit evidence package generated by {PROJECT_NAME}. All entropy calculations, pattern matches, and confidence scores are deterministic and reproducible.

---

**Timestamp**: {deception_report.timestamp}
**Audit Trail**: {PROJECT_NAME} v{PROJECT_VERSION}
**Operator**: {PROJECT_OPERATOR}
"""
