"""
Generate human-readable forensic reports as Markdown, PDF, and DOCX.

No cloud AI -- deterministic formatting only.
"""
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional


@dataclass
class DocumentAuditReport:
    filename: str
    extracted_text: str
    text_length: int
    deception_report: dict
    bbfb_report: Optional[dict] = None
    acl_demand: Optional[str] = None
    generated_at: str = ""
    warnings: List[str] = field(default_factory=list)

    def __post_init__(self) -> None:
        if not self.generated_at:
            self.generated_at = datetime.now(timezone.utc).isoformat()


def _safe_filename(name: str) -> str:
    return re.sub(r"[^\w\-\.]", "_", name).strip("_")


def build_markdown(report: DocumentAuditReport) -> str:
    """Return a Markdown forensic report string."""
    dr = report.deception_report
    entropy = dr.get("entropy", {})
    patterns = dr.get("detectedPatterns", [])
    reasoning = dr.get("forensicReasoning", [])

    md = ["# Forensic Audit Report", ""]
    md.append(f"**Source File**: `{report.filename}`")
    md.append(f"**Generated**: {report.generated_at}")
    md.append(f"**Extracted Characters**: {report.text_length}")
    md.append(f"**Engine**: Order Get It Right v1.0.0")
    md.append("")

    if report.warnings:
        md.append("## Warnings")
        for w in report.warnings:
            md.append(f"- {w}")
        md.append("")

    md.append("## 1. Deception Scan")
    md.append("")
    md.append("| Metric | Value |")
    md.append("|--------|-------|")
    md.append(f"| Shannon Entropy | {entropy.get('shannonEntropy', 0):.3f} bits/char |")
    md.append(f"| Normalized Entropy | {entropy.get('normalizedEntropy', 0):.3f} |")
    md.append(f"| Anomaly Flag | {'YES' if entropy.get('anomalyFlag') else 'No'} |")
    md.append(f"| Low Entropy Flag | {'YES' if entropy.get('lowEntropyFlag') else 'No'} |")
    md.append(f"| Deception Probability | {dr.get('deceptionProbability', 0) * 100:.1f}% |")
    md.append(f"| Structural Deception Flag | {'TRUE' if dr.get('structuralDeceptionFlag') else 'FALSE'} |")
    md.append(f"| Patterns Detected | {len(patterns)} / 54 |")
    md.append("")

    if patterns:
        md.append("### Matched Deception Patterns")
        md.append("")
        md.append("| ID | Pattern | Severity | Confidence | Indicators |")
        md.append("|----|---------|----------|------------|------------|")
        for p in patterns:
            ind = ", ".join(p.get("matchedIndicators", [])[:5])
            md.append(
                f"| {p.get('patternId')} | {p.get('patternName')} | {p.get('severity')} | "
                f"{p.get('confidence', 0) * 100:.1f}% | {ind} |"
            )
        md.append("")

    if reasoning:
        md.append("### Forensic Reasoning")
        for r in reasoning:
            md.append(f"- {r}")
        md.append("")

    if report.bbfb_report:
        b = report.bbfb_report
        md.append("## 2. BBFB Product Evaluation")
        md.append("")
        law_rows = b.get("law", [])
        md.append("| LAW Gate | Value | Threshold | Passed |")
        md.append("|----------|-------|-----------|--------|")
        for g in law_rows:
            md.append(
                f"| {g.get('metric')} | {g.get('value', 0):.4f} | "
                f"{g.get('threshold')} | {'YES' if g.get('passed') else 'NO'} |"
            )
        md.append("")
        grace = b.get("grace", {})
        fruit = b.get("fruit", {})
        md.append(f"| GRACE Risk Level | {grace.get('riskLevel', 'N/A')} |")
        md.append(f"| GRACE Normalized Penalty | {grace.get('normalizedPenalty', 0):.4f} |")
        md.append(f"| FRUIT Composite Value Score | {fruit.get('compositeValueScore', 0):.6f} |")
        md.append(f"| CVS Threshold | {fruit.get('threshold', 0)} |")
        md.append(f"| BBFB Compliant | {'YES' if b.get('overallCompliant') else 'NO'} |")
        md.append("")

    if report.acl_demand:
        md.append("## 3. ACL Section 56 Demand Letter")
        md.append("")
        md.append(report.acl_demand)
        md.append("")

    md.append("## Document Audit Trail")
    md.append("")
    md.append("- **Deterministic Engine**: Shannon entropy + 54-pattern ontology")
    md.append("- **No cloud AI invoked** in the core audit path")
    md.append(f"- **Timestamp**: {report.generated_at}")
    md.append("")
    md.append("---")
    md.append(
        "*This report was generated by Order Get It Right for forensic review. "
        "A human must review any legal demand before issue.*"
    )
    return "\n".join(md)


def write_markdown(report: DocumentAuditReport, out_path: Path) -> Path:
    out_path.write_text(build_markdown(report), encoding="utf-8")
    return out_path


def write_pdf(report: DocumentAuditReport, out_path: Path) -> Path:
    from reportlab.lib.pagesizes import letter
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
    from reportlab.lib.styles import getSampleStyleSheet

    md = build_markdown(report)
    paragraphs = []
    buf = []
    for line in md.splitlines():
        line = line.strip()
        if not line:
            if buf:
                paragraphs.append(" ".join(buf))
                buf = []
            continue
        if line.startswith("#"):
            if buf:
                paragraphs.append(" ".join(buf))
                buf = []
            paragraphs.append(line.lstrip("#").strip())
        elif line.startswith("|"):
            cells = [c.strip() for c in line.split("|")[1:-1]]
            if cells and not set(cells) <= {"-", ":"}:
                buf.append(" | ".join(cells))
        elif line.startswith(("-", "*")):
            if buf:
                paragraphs.append(" ".join(buf))
                buf = []
            paragraphs.append("\u2022 " + line.lstrip("-* ").strip())
        else:
            buf.append(line)
    if buf:
        paragraphs.append(" ".join(buf))
    paragraphs = [p for p in paragraphs if p.strip()]

    doc = SimpleDocTemplate(
        str(out_path),
        pagesize=letter,
        rightMargin=72, leftMargin=72,
        topMargin=72, bottomMargin=18,
    )
    styles = getSampleStyleSheet()
    story = []
    for p in paragraphs:
        if p.startswith("## ") or p.startswith("# "):
            story.append(Spacer(1, 12))
            story.append(Paragraph(p, styles["Heading2"]))
        else:
            story.append(Paragraph(p, styles["BodyText"]))
        story.append(Spacer(1, 6))
    doc.build(story)
    return out_path


def write_docx(report: DocumentAuditReport, out_path: Path) -> Path:
    from docx import Document

    doc = Document()
    doc.add_heading("Forensic Audit Report", level=0)
    doc.add_paragraph(f"Source File: {report.filename}")
    doc.add_paragraph(f"Generated: {report.generated_at}")
    doc.add_paragraph(f"Extracted Characters: {report.text_length}")

    doc.add_heading("1. Deception Scan", level=1)
    dr = report.deception_report
    entropy = dr.get("entropy", {})
    doc.add_paragraph(f"Shannon Entropy: {entropy.get('shannonEntropy', 0):.3f} bits/char")
    doc.add_paragraph(f"Deception Probability: {dr.get('deceptionProbability', 0) * 100:.1f}%")
    doc.add_paragraph(f"Patterns Detected: {len(dr.get('detectedPatterns', []))} / 54")
    doc.add_paragraph(f"Structural Deception Flag: {dr.get('structuralDeceptionFlag', False)}")

    doc.add_heading("2. BBFB Product Evaluation", level=1)
    if report.bbfb_report:
        b = report.bbfb_report
        doc.add_paragraph(f"Overall Compliant: {b.get('overallCompliant', False)}")
        doc.add_paragraph(f"GRACE Risk Level: {b.get('grace', {}).get('riskLevel', 'N/A')}")
        doc.add_paragraph(
            f"FRUIT Composite Value Score: {b.get('fruit', {}).get('compositeValueScore', 0):.6f}"
        )
    else:
        doc.add_paragraph("No product evidence detected; BBFB evaluation not run.")

    doc.add_heading("3. ACL Section 56 Demand Letter", level=1)
    if report.acl_demand:
        doc.add_paragraph(report.acl_demand)
    else:
        doc.add_paragraph("No ACL demand generated.")

    doc.add_paragraph("")
    doc.add_paragraph(
        "This report was generated by Order Get It Right. A human must review any legal demand before issue."
    )
    doc.save(str(out_path))
    return out_path


SUPPORTED_OUTPUTS = {
    ".md": write_markdown,
    ".pdf": write_pdf,
    ".docx": write_docx,
}


def write_report(
    report: DocumentAuditReport,
    out_dir: Path,
    base_name: str,
    formats: Optional[List[str]] = None,
) -> List[Path]:
    """Write the report in each requested format."""
    if formats is None:
        formats = list(SUPPORTED_OUTPUTS.keys())
    out_dir.mkdir(parents=True, exist_ok=True)
    paths = []
    for fmt in formats:
        fmt = fmt.lower()
        if not fmt.startswith("."):
            fmt = "." + fmt
        writer = SUPPORTED_OUTPUTS.get(fmt)
        if writer is None:
            report.warnings.append(f"Unsupported output format requested: {fmt}")
            continue
        out_path = out_dir / f"{base_name}{fmt}"
        writer(report, out_path)
        paths.append(out_path)
    return paths
